"""empty message

Revision ID: 4bd45cec6a7a
Revises: d1df309ec211
Create Date: 2021-11-16 00:54:44.470407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd45cec6a7a'
down_revision = 'd1df309ec211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
