"""empty message

Revision ID: 571978fb6cd5
Revises: d1900391ba40
Create Date: 2021-11-15 23:39:18.250968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571978fb6cd5'
down_revision = 'd1900391ba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
