"""empty message

Revision ID: 7f0714aa6789
Revises: bd4fd4d8d824
Create Date: 2021-11-23 23:43:21.304986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0714aa6789'
down_revision = 'bd4fd4d8d824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('subcategoryequipmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'subcategoryequipment', ['subcategoryequipmentid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'subcategoryequipmentid')
    # ### end Alembic commands ###
