"""empty message

Revision ID: bd4fd4d8d824
Revises: aab40636b6da
Create Date: 2021-11-22 22:09:23.142598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4fd4d8d824'
down_revision = 'aab40636b6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategoryequipment', sa.Column('categoryequipmentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subcategoryequipment', 'categoryequipment', ['categoryequipmentid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategoryequipment', type_='foreignkey')
    op.drop_column('subcategoryequipment', 'categoryequipmentid')
    # ### end Alembic commands ###
